In [13]:
import numpy as np
lst = (6,9,4,2,0)
arr = np.array(lst)
print(arr)
print("\n",type(arr))

[6 9 4 2 0]

 <class 'numpy.ndarray'>


In [14]:
import numpy as np
arr = np.array(([1,2,3],[4,5,6]))
print(arr)

[[1 2 3]
 [4 5 6]]


In [15]:
import numpy as np
lst = ([1,2,3,4],[5,6,7,8])
arr = np.array(lst)
print(arr)

[[1 2 3 4]
 [5 6 7 8]]


In [16]:
import numpy as np
x = np.array([[1, 2, 3],[4, 5, 6]], np.int32)
print(type(x))
x.shape


<class 'numpy.ndarray'>


(2, 3)

In [17]:
import numpy as np

x = np.array([[1, 2, 3], [4, 5, 6]], np.int32)

print(x)
print(x.shape)
print(x.dtype)


[[1 2 3]
 [4 5 6]]
(2, 3)
int32


In [18]:
import numpy as np

x = np.array([20.5, 30.5, 40.5, 50.5, 60.5], dtype = float)
print(x)



[20.5 30.5 40.5 50.5 60.5]


In [19]:
import numpy as np

a = np.array(50)
b = np.array([9,8,7,6,5])
c = np.array([[1, 2, 3],[4,5,6]])
d = np.array([[[1, 2, 3], [4,5,6]], [[1,2,3],[4,5,6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

#dimension can be defined by the no.of square brackets

0
1
2
3


In [20]:
import numpy as np

a = np.array([[[1,2,3],[3,4,5],[5,6,7]],[[1,2,3],[1,2,3],[1,2,3]],[[1,2,3],[1,2,3],[1,2,3]],[[1,2,3],[1,2,3],[1,2,3]],[[1,2,3],[1,2,3],[1,2,3]]], ndmin = 5)

print(a)
print("Number of dimensions :", a.ndim)

[[[[[1 2 3]
    [3 4 5]
    [5 6 7]]

   [[1 2 3]
    [1 2 3]
    [1 2 3]]

   [[1 2 3]
    [1 2 3]
    [1 2 3]]

   [[1 2 3]
    [1 2 3]
    [1 2 3]]

   [[1 2 3]
    [1 2 3]
    [1 2 3]]]]]
Number of dimensions : 5


In [21]:
import numpy as np

arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

print(arr[0,1,2])

6


In [25]:
import numpy as np

arr = np.array([1,2,3,4,5,6,7])

print(arr[1:5])

print(arr[-3:-1])

print(arr[1:5:2])

print(arr[::2])

[2 3 4 5]
[5 6]
[2 4]
[1 3 5 7]


In [29]:
import numpy as np

arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])

print(arr[1, 1:4])

print(arr[0:2, 2])

[7 8 9]
[3 8]


In [37]:
import numpy as np

arr = np.array([1,2,3,4,5,6], ndmin = 5)

print(arr.dtype)
print(arr.shape)

int32
(1, 1, 1, 1, 6)


In [6]:
import numpy as np

arr = np.array([1,2,3,4,5], dtype='S')

print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4' b'5']
|S1


In [14]:
import numpy as np

arr = np.array([-1,2,3,4,5], dtype='i4')

print(arr)
print(arr.dtype)

[-1  2  3  4  5]
int32


In [28]:
import numpy as np

arr = np.array([-1,2.5,3,0,5])

arr1 = arr.astype(bool)
print(arr1)
print(arr1.dtype)

[ True  True  True False  True]
bool


In [34]:
import numpy as np

arr = np.array([1,2,3,4,5])
x= arr.view()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


In [11]:
import numpy as np

arr = np.array([1,2,3,4,5,6,7,8])
#dimensionality reduction algorithm (base method reshape())
newarr = arr.reshape(2, 2, 2)

print(newarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [24]:
import numpy as np

arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
newarr = arr.reshape(-1)

print(newarr)
print(newarr.ndim)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
1


In [34]:
import numpy as np
arr = np.array([1,2,3])

for i in arr:
    print(i, end =" ")

1 2 3 

In [35]:
import numpy as np

arr = np.array([[1,2,3],[4,5,6]])

print(arr, "\n")
for i in arr:
    print(i, end=" ")

[[1 2 3]
 [4 5 6]] 

[1 2 3] [4 5 6] 

In [37]:
import numpy as np

arr = np.array([[1,2,3],[4,5,6]])

for x in arr:
    for y in x:
        print(y, end=" ")

1 2 3 4 5 6 

In [38]:
import numpy as np

arr = np.array([[[1,2,3],[10,11,12]],[[4,5,6],[7,8,9]]])

for x in arr:
    for y in x:
        for z in y:
            print(z, end=" ")

1 2 3 10 11 12 4 5 6 7 8 9 

In [40]:
import numpy as np

arr = np.array([[[1,2,3],[10,11,12]],[[4,5,6],[7,8,9]]])

for x in np.nditer(arr):
    print(x, end=" ")

1 2 3 10 11 12 4 5 6 7 8 9 

In [41]:
import numpy as np

arr = np.array([[[1,2,3],[10,11,12]],[[4,5,6],[7,8,9]]])

for x in np.nditer(arr, flags=['buffered'], op_dtypes=['S']):
    print(x, end=" ")

b'1' b'2' b'3' b'10' b'11' b'12' b'4' b'5' b'6' b'7' b'8' b'9' 

In [42]:
import numpy as np

arr = np.array([[[1,2,3],[10,11,12]],[[4,5,6],[7,8,9]]])

for x in np.nditer(arr[:, ::2]):
    print(x, end=" ")

1 2 3 4 5 6 

In [44]:
import numpy as np

arr = np.array([[[1,2,3],[10,11,12]],[[4,5,6],[7,8,9]]])

for x, y in np.ndenumerate(arr):
    print(y,x)

1 (0, 0, 0)
2 (0, 0, 1)
3 (0, 0, 2)
10 (0, 1, 0)
11 (0, 1, 1)
12 (0, 1, 2)
4 (1, 0, 0)
5 (1, 0, 1)
6 (1, 0, 2)
7 (1, 1, 0)
8 (1, 1, 1)
9 (1, 1, 2)


In [5]:
import numpy as np

arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2), axis=1)

print(arr)

[[1 2 5 6]
 [3 4 7 8]]


In [10]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.stack((arr1, arr2), axis=1)

print(arr)

[[1 4]
 [2 5]
 [3 6]]


In [11]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.hstack((arr1, arr2))

print(arr)

[1 2 3 4 5 6]
