In [13]:
import numpy as np
lst = (6,9,4,2,0)
arr = np.array(lst)
print(arr)
print("\n",type(arr))

[6 9 4 2 0]

 <class 'numpy.ndarray'>


In [14]:
import numpy as np
arr = np.array(([1,2,3],[4,5,6]))
print(arr)

[[1 2 3]
 [4 5 6]]


In [15]:
import numpy as np
lst = ([1,2,3,4],[5,6,7,8])
arr = np.array(lst)
print(arr)

[[1 2 3 4]
 [5 6 7 8]]


In [16]:
import numpy as np
x = np.array([[1, 2, 3],[4, 5, 6]], np.int32)
print(type(x))
x.shape


<class 'numpy.ndarray'>


(2, 3)

In [17]:
import numpy as np

x = np.array([[1, 2, 3], [4, 5, 6]], np.int32)

print(x)
print(x.shape)
print(x.dtype)


[[1 2 3]
 [4 5 6]]
(2, 3)
int32


In [18]:
import numpy as np

x = np.array([20.5, 30.5, 40.5, 50.5, 60.5], dtype = float)
print(x)



[20.5 30.5 40.5 50.5 60.5]


In [19]:
import numpy as np

a = np.array(50)
b = np.array([9,8,7,6,5])
c = np.array([[1, 2, 3],[4,5,6]])
d = np.array([[[1, 2, 3], [4,5,6]], [[1,2,3],[4,5,6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

#dimension can be defined by the no.of square brackets

0
1
2
3


In [20]:
import numpy as np

a = np.array([[[1,2,3],[3,4,5],[5,6,7]],[[1,2,3],[1,2,3],[1,2,3]],[[1,2,3],[1,2,3],[1,2,3]],[[1,2,3],[1,2,3],[1,2,3]],[[1,2,3],[1,2,3],[1,2,3]]], ndmin = 5)

print(a)
print("Number of dimensions :", a.ndim)

[[[[[1 2 3]
    [3 4 5]
    [5 6 7]]

   [[1 2 3]
    [1 2 3]
    [1 2 3]]

   [[1 2 3]
    [1 2 3]
    [1 2 3]]

   [[1 2 3]
    [1 2 3]
    [1 2 3]]

   [[1 2 3]
    [1 2 3]
    [1 2 3]]]]]
Number of dimensions : 5


In [21]:
import numpy as np

arr = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

print(arr[0,1,2])

6


In [25]:
import numpy as np

arr = np.array([1,2,3,4,5,6,7])

print(arr[1:5])

print(arr[-3:-1])

print(arr[1:5:2])

print(arr[::2])

[2 3 4 5]
[5 6]
[2 4]
[1 3 5 7]


In [29]:
import numpy as np

arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])

print(arr[1, 1:4])

print(arr[0:2, 2])

[7 8 9]
[3 8]
